# Generated by Django 4.2.18 on 2026-09-22 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('PISCICULTURE', 'Pisciculture')], max_length=20)),
                ('quantity_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('SOLD_OUT', 'Épuisé'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
